<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="joseangeldiazg" />


<title>Car Evaluation: Reglas de Asociación</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Minería de Datos: Aprendizaje no supervisado.</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="outliers.html">Detección de Anomalías</a>
</li>
<li>
  <a href="car-rules.html">Reglas de Asociación</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Car Evaluation: Reglas de Asociación</h1>
<h4 class="author"><em>joseangeldiazg</em></h4>
<h4 class="date"><em>20/2/2018</em></h4>

</div>


<div id="introduccion-al-dataset" class="section level2">
<h2>1 Introducción al dataset</h2>
<p>Para la práctica de reglas de asociación de la asignatura <strong>“Minería de Datos: Detección de Anomálias y Aprendizaje no Supervisado”</strong> se ha utilizado un dataset recuperado de la web de UCI que tiene ciertas características de coches y trata de evaluar los mismos en función de factores como su comodidad.</p>
<p>El dataset puede encontrarse en el siguiente enlace: <a href="https://archive.ics.uci.edu/ml/datasets/Car+Evaluation" class="uri">https://archive.ics.uci.edu/ml/datasets/Car+Evaluation</a></p>
<p>Leemos los datos y construimos un dataframe, ya que estos vienen separados en data y names.</p>
<pre class="r"><code>maint&lt;-read.table(&quot;data/car.data&quot;, sep = &quot;,&quot;)
names(car)&lt;-c(&quot;precio-compra&quot;,&quot;precio-mantenimiento&quot;,&quot;puertas&quot;,
              &quot;pasajeros&quot;, &quot;maletero&quot;, &quot;seguridad&quot;, &quot;clase&quot;)</code></pre>
</div>
<div id="analisis-exploratorio" class="section level2">
<h2>2 Análisis exploratorio</h2>
<p>Vamos a comprobar si tenemos datos completos en los datos, ya que los valores perdidos siempre pueden causar problemas.</p>
<pre class="r"><code>sum(is.na(car))</code></pre>
<pre><code>## [1] 0</code></pre>
<p>Vemos que no hay valores perdidos por lo que el siguiente paso será ver de que tipo son nuestros datos, así como sus distribuciones para comenzar a hacernos una idea de que es lo que tenemos entre manos.</p>
<pre class="r"><code>str(car)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1728 obs. of  7 variables:
##  $ precio-compra       : Factor w/ 4 levels &quot;high&quot;,&quot;low&quot;,&quot;med&quot;,..: 4 4 4 4 4 4 4 4 4 4 ...
##  $ precio-mantenimiento: Factor w/ 4 levels &quot;high&quot;,&quot;low&quot;,&quot;med&quot;,..: 4 4 4 4 4 4 4 4 4 4 ...
##  $ puertas             : Factor w/ 4 levels &quot;2&quot;,&quot;3&quot;,&quot;4&quot;,&quot;5more&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ pasajeros           : Factor w/ 3 levels &quot;2&quot;,&quot;4&quot;,&quot;more&quot;: 1 1 1 1 1 1 1 1 1 2 ...
##  $ maletero            : Factor w/ 3 levels &quot;big&quot;,&quot;med&quot;,&quot;small&quot;: 3 3 3 2 2 2 1 1 1 3 ...
##  $ seguridad           : Factor w/ 3 levels &quot;high&quot;,&quot;low&quot;,&quot;med&quot;: 2 3 1 2 3 1 2 3 1 2 ...
##  $ clase               : Factor w/ 4 levels &quot;acc&quot;,&quot;good&quot;,&quot;unacc&quot;,..: 3 3 3 3 3 3 3 3 3 3 ...</code></pre>
<p>Parece que todos son factores, por lo que no tendremos variables numéricas que partir en rangos que puedan ser caracterizados.</p>
<pre class="r"><code>library(Hmisc)
describe(car)</code></pre>
<pre><code>## car 
## 
##  7  Variables      1728  Observations
## ---------------------------------------------------------------------------
## precio-compra 
##        n  missing distinct 
##     1728        0        4 
##                                   
## Value       high   low   med vhigh
## Frequency    432   432   432   432
## Proportion  0.25  0.25  0.25  0.25
## ---------------------------------------------------------------------------
## precio-mantenimiento 
##        n  missing distinct 
##     1728        0        4 
##                                   
## Value       high   low   med vhigh
## Frequency    432   432   432   432
## Proportion  0.25  0.25  0.25  0.25
## ---------------------------------------------------------------------------
## puertas 
##        n  missing distinct 
##     1728        0        4 
##                                   
## Value          2     3     4 5more
## Frequency    432   432   432   432
## Proportion  0.25  0.25  0.25  0.25
## ---------------------------------------------------------------------------
## pasajeros 
##        n  missing distinct 
##     1728        0        3 
##                             
## Value          2     4  more
## Frequency    576   576   576
## Proportion 0.333 0.333 0.333
## ---------------------------------------------------------------------------
## maletero 
##        n  missing distinct 
##     1728        0        3 
##                             
## Value        big   med small
## Frequency    576   576   576
## Proportion 0.333 0.333 0.333
## ---------------------------------------------------------------------------
## seguridad 
##        n  missing distinct 
##     1728        0        3 
##                             
## Value       high   low   med
## Frequency    576   576   576
## Proportion 0.333 0.333 0.333
## ---------------------------------------------------------------------------
## clase 
##        n  missing distinct 
##     1728        0        4 
##                                   
## Value        acc  good unacc vgood
## Frequency    384    69  1210    65
## Proportion 0.222 0.040 0.700 0.038
## ---------------------------------------------------------------------------</code></pre>
<p>Respecto a las distribuciones, vemos que salvo la clase, final, donde tenemos mas coches catalogados como malos que buenos, todas las demás variables se distribuyen de manera homogénea y no balanceda. Esto nos beneficiará en el proceso de minado de reglas de asociación ya que tendremos representaciones homogéneas de los ítems. Dicho esto, estamos en posición de comenzar nuestro estudio de reglas de asociación e itemsets frecuentes.</p>
</div>
<div id="paso-a-base-de-datos-transaccional" class="section level2">
<h2>3 Paso a base de datos transaccional</h2>
<p>Para el proceso de obtención de reglas de asociación, la base de datos debe ser transaccional. Nuestro dataset, según lo estudiado en el punto anterior se presta a ello de manera fácil, por lo que no tendremos que preparar mucho los datos.</p>
<pre class="r"><code>library(arules)
car.transactions &lt;- as(car, &quot;transactions&quot;)
summary(car.transactions)</code></pre>
<pre><code>## transactions as itemMatrix in sparse format with
##  1728 rows (elements/itemsets/transactions) and
##  25 columns (items) and a density of 0.28 
## 
## most frequent items:
##    clase=unacc    pasajeros=2    pasajeros=4 pasajeros=more   maletero=big 
##           1210            576            576            576            576 
##        (Other) 
##           8582 
## 
## element (itemset/transaction) length distribution:
## sizes
##    7 
## 1728 
## 
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       7       7       7       7       7       7 
## 
## includes extended item information - examples:
##               labels     variables levels
## 1 precio-compra=high precio-compra   high
## 2  precio-compra=low precio-compra    low
## 3  precio-compra=med precio-compra    med
## 
## includes extended transaction information - examples:
##   transactionID
## 1             1
## 2             2
## 3             3</code></pre>
</div>
<div id="itemsets" class="section level2">
<h2>4 Itemsets</h2>
<p>En esta sección usaremos las transacciones de nuestro dataset para realizar un análisis de los itemsets. Para ello, nos centraremos en los <strong>itemsets frecuentes, maximales y cerrados</strong>.</p>
<p>El pauquete <strong>arules</strong> tiene una función muy útil que nos permite ver la distribución de ítems-frecuentes de manera gráfica para un valor determinado de soporte mínimo.</p>
<pre class="r"><code>itemFrequencyPlot(car.transactions, support = 0.1, cex.names=0.8)</code></pre>
<p><img src="car-arules_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Si analizamos el anterior gráfico, podemos comprobar como solo <strong>clase=unacc</strong>, está presente en más de la mitad de las transacciones. Por otro lado, las demás variables se mantienen estables lo que gráficamente nos induce a pensar que es un dataset bastante artificial o confeccionado a conciencia para tener estas frecuencias de ítems. Cabe remarcar que no hay presencia de los ítems <strong>clase=good</strong> o <strong>clase=vgood</strong>, que a muy seguro tendrán valores de soporte menor de 0.1. Dado que estos ítems son muy interesantes para obtener información del problema, ya podemos remarcar que el valor de soporte para la obtención de las reglas deberá ser menor de 0.1. Vamos a comprobar que esta premisa es así, representando el mismo gráfico pero con menos soporte.</p>
<pre class="r"><code>itemFrequencyPlot(car.transactions, support = 0.01, cex.names=0.8)</code></pre>
<p><img src="car-arules_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>En el anterior gráfico podemos apreciar como han aparecido dos nuevas columnas, que reprentan los ítems <strong>clase=good</strong> y <strong>clase=vgood</strong> lo que nos lleva a concluir por tanto que los valores de soporte de estos ítems en función al resto son muy bajos, algo que los convierte en muy interesantes y dignos de estudio ya que además resentan a dos clases aceptables del problema.</p>
<p>Vamos a obtener el algoritmo <strong>apriori</strong>, para obtener los itemsets frecuentes y analizarlos con más detalle atendiendo a sus medidas.</p>
<pre class="r"><code>iCar &lt;- apriori(car.transactions, parameter = list(support = 0.01, target=&quot;frequent&quot;, minlen=1))</code></pre>
<pre><code>## Apriori
## 
## Parameter specification:
##  confidence minval smax arem  aval originalSupport maxtime support minlen
##          NA    0.1    1 none FALSE            TRUE       5    0.01      1
##  maxlen            target   ext
##      10 frequent itemsets FALSE
## 
## Algorithmic control:
##  filter tree heap memopt load sort verbose
##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
## 
## Absolute minimum support count: 17 
## 
## set item appearances ...[0 item(s)] done [0.00s].
## set transactions ...[25 item(s), 1728 transaction(s)] done [0.00s].
## sorting and recoding items ... [25 item(s)] done [0.00s].
## creating transaction tree ... done [0.00s].
## checking subsets of size 1 2 3 4 done [0.00s].
## writing ... [2291 set(s)] done [0.00s].
## creating S4 object  ... done [0.00s].</code></pre>
<pre class="r"><code>#Ordenamos los ítems por soporte descendente
iCar &lt;- sort(iCar, by=&quot;support&quot;)</code></pre>
<p>Hemos generado un total de 2291 itemsets frecuentes. Vamos a ver cuales son estos, usando el comando <strong>inspect</strong>.</p>
<pre class="r"><code>#Inspeccionamos los 100 primeros
inspect(head(iCar, n=50))</code></pre>
<pre><code>##      items                                    support   count
## [1]  {clase=unacc}                            0.7002315 1210 
## [2]  {pasajeros=more}                         0.3333333  576 
## [3]  {pasajeros=4}                            0.3333333  576 
## [4]  {maletero=big}                           0.3333333  576 
## [5]  {maletero=med}                           0.3333333  576 
## [6]  {seguridad=high}                         0.3333333  576 
## [7]  {seguridad=med}                          0.3333333  576 
## [8]  {seguridad=low}                          0.3333333  576 
## [9]  {maletero=small}                         0.3333333  576 
## [10] {pasajeros=2}                            0.3333333  576 
## [11] {seguridad=low,clase=unacc}              0.3333333  576 
## [12] {pasajeros=2,clase=unacc}                0.3333333  576 
## [13] {maletero=small,clase=unacc}             0.2604167  450 
## [14] {precio-compra=vhigh}                    0.2500000  432 
## [15] {precio-compra=med}                      0.2500000  432 
## [16] {precio-compra=high}                     0.2500000  432 
## [17] {precio-mantenimiento=low}               0.2500000  432 
## [18] {precio-mantenimiento=med}               0.2500000  432 
## [19] {precio-mantenimiento=high}              0.2500000  432 
## [20] {puertas=5more}                          0.2500000  432 
## [21] {puertas=4}                              0.2500000  432 
## [22] {puertas=3}                              0.2500000  432 
## [23] {puertas=2}                              0.2500000  432 
## [24] {precio-mantenimiento=vhigh}             0.2500000  432 
## [25] {precio-compra=low}                      0.2500000  432 
## [26] {maletero=med,clase=unacc}               0.2268519  392 
## [27] {clase=acc}                              0.2222222  384 
## [28] {maletero=big,clase=unacc}               0.2129630  368 
## [29] {precio-compra=vhigh,clase=unacc}        0.2083333  360 
## [30] {precio-mantenimiento=vhigh,clase=unacc} 0.2083333  360 
## [31] {seguridad=med,clase=unacc}              0.2065972  357 
## [32] {puertas=2,clase=unacc}                  0.1886574  326 
## [33] {precio-compra=high,clase=unacc}         0.1875000  324 
## [34] {pasajeros=more,clase=unacc}             0.1863426  322 
## [35] {precio-mantenimiento=high,clase=unacc}  0.1817130  314 
## [36] {pasajeros=4,clase=unacc}                0.1805556  312 
## [37] {puertas=3,clase=unacc}                  0.1736111  300 
## [38] {puertas=5more,clase=unacc}              0.1689815  292 
## [39] {puertas=4,clase=unacc}                  0.1689815  292 
## [40] {seguridad=high,clase=unacc}             0.1603009  277 
## [41] {precio-compra=med,clase=unacc}          0.1550926  268 
## [42] {precio-mantenimiento=low,clase=unacc}   0.1550926  268 
## [43] {precio-mantenimiento=med,clase=unacc}   0.1550926  268 
## [44] {precio-compra=low,clase=unacc}          0.1493056  258 
## [45] {seguridad=high,clase=acc}               0.1180556  204 
## [46] {pasajeros=4,clase=acc}                  0.1145833  198 
## [47] {pasajeros=more,maletero=big}            0.1111111  192 
## [48] {pasajeros=more,maletero=med}            0.1111111  192 
## [49] {pasajeros=more,seguridad=high}          0.1111111  192 
## [50] {pasajeros=more,seguridad=med}           0.1111111  192</code></pre>
<p>Si nos centraramos solo en los ítemsets frecuentes, ya podríamos obtener información relevante del dataset e incluso hacer algunas “predicciones” en un hipotético caso de toma de decisiones, como por ejemplo el set de ítems <em>[29] {precio-compra=vhigh,clase=unacc} </em> en contra de lo que podríamos llegar a pensar aparecen bastantes veces en el dataset que si el precio de compra es muy caro, la clase será la peor, por lo que ya podríamos casi asegurar que con mucha probabilidad que un coche sea evaluado como bueno o malo vendrá dado por otros motivos en lugar de un precio caro.</p>
<p>Otro set de ítems interesantes, podría ser el <em>[12] {pasajeros=2,clase=unacc}</em>, aquí estamos claramente frente a coches deportivos de dos plazas que en un gran número de casos, son asignados a la peor clase, por lo que esto nos deja saber que probablemente lo que tenemos entre manos son evaluaciones que nada tienen que ver con lujos o grandes motores sino con coches serviciales y destinados al uso diario.</p>
<p>Si quisieramos acotar y seguir analizando los ítemsets frecuentes, podríamos usar rangos definidos por las variables <strong>minlen</strong> y <strong>maxlen</strong> para definir cuantos ítems queremos que formen los sets.</p>
<pre class="r"><code>iCar &lt;- apriori(car.transactions, parameter = list(support = 0.01, 
                                                   target=&quot;frequent&quot;, 
                                                   minlen=2, 
                                                   maxlen=4))</code></pre>
<pre><code>## Apriori
## 
## Parameter specification:
##  confidence minval smax arem  aval originalSupport maxtime support minlen
##          NA    0.1    1 none FALSE            TRUE       5    0.01      2
##  maxlen            target   ext
##       4 frequent itemsets FALSE
## 
## Algorithmic control:
##  filter tree heap memopt load sort verbose
##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
## 
## Absolute minimum support count: 17 
## 
## set item appearances ...[0 item(s)] done [0.00s].
## set transactions ...[25 item(s), 1728 transaction(s)] done [0.00s].
## sorting and recoding items ... [25 item(s)] done [0.00s].
## creating transaction tree ... done [0.00s].
## checking subsets of size 1 2 3 4</code></pre>
<pre><code>## Warning in apriori(car.transactions, parameter = list(support = 0.01,
## target = &quot;frequent&quot;, : Mining stopped (maxlen reached). Only patterns up to
## a length of 4 returned!</code></pre>
<pre><code>##  done [0.00s].
## writing ... [2266 set(s)] done [0.00s].
## creating S4 object  ... done [0.00s].</code></pre>
<pre class="r"><code>#Ordenamos los ítems por soporte descendente
iCar &lt;- sort(iCar, by=&quot;support&quot;)
#Mostramos a modo de ejemplo los 20 primeros
inspect(head(iCar, n=20))</code></pre>
<pre><code>##      items                                    support   count
## [1]  {seguridad=low,clase=unacc}              0.3333333 576  
## [2]  {pasajeros=2,clase=unacc}                0.3333333 576  
## [3]  {maletero=small,clase=unacc}             0.2604167 450  
## [4]  {maletero=med,clase=unacc}               0.2268519 392  
## [5]  {maletero=big,clase=unacc}               0.2129630 368  
## [6]  {precio-compra=vhigh,clase=unacc}        0.2083333 360  
## [7]  {precio-mantenimiento=vhigh,clase=unacc} 0.2083333 360  
## [8]  {seguridad=med,clase=unacc}              0.2065972 357  
## [9]  {puertas=2,clase=unacc}                  0.1886574 326  
## [10] {precio-compra=high,clase=unacc}         0.1875000 324  
## [11] {pasajeros=more,clase=unacc}             0.1863426 322  
## [12] {precio-mantenimiento=high,clase=unacc}  0.1817130 314  
## [13] {pasajeros=4,clase=unacc}                0.1805556 312  
## [14] {puertas=3,clase=unacc}                  0.1736111 300  
## [15] {puertas=5more,clase=unacc}              0.1689815 292  
## [16] {puertas=4,clase=unacc}                  0.1689815 292  
## [17] {seguridad=high,clase=unacc}             0.1603009 277  
## [18] {precio-compra=med,clase=unacc}          0.1550926 268  
## [19] {precio-mantenimiento=low,clase=unacc}   0.1550926 268  
## [20] {precio-mantenimiento=med,clase=unacc}   0.1550926 268</code></pre>
<p>Estos parámetros anteriores pueden ser muy útiles en grandes conjuntos de datos donde la explosión de itemsets sea muy grande. En nuestro caso, dejaremos los parámetros por defecto dado que a simple vista podemos manejarlos todos sin muchas complicaciones. Obtendremos por tanto los de todos los tamaños y crearemos un gráfico de barras para ver su distribución.</p>
<pre class="r"><code>iCar &lt;- apriori(car.transactions, parameter = list(support = 0.01, target=&quot;frequent&quot;))</code></pre>
<pre><code>## Apriori
## 
## Parameter specification:
##  confidence minval smax arem  aval originalSupport maxtime support minlen
##          NA    0.1    1 none FALSE            TRUE       5    0.01      1
##  maxlen            target   ext
##      10 frequent itemsets FALSE
## 
## Algorithmic control:
##  filter tree heap memopt load sort verbose
##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
## 
## Absolute minimum support count: 17 
## 
## set item appearances ...[0 item(s)] done [0.00s].
## set transactions ...[25 item(s), 1728 transaction(s)] done [0.00s].
## sorting and recoding items ... [25 item(s)] done [0.00s].
## creating transaction tree ... done [0.00s].
## checking subsets of size 1 2 3 4 done [0.00s].
## writing ... [2291 set(s)] done [0.00s].
## creating S4 object  ... done [0.00s].</code></pre>
<pre class="r"><code>barplot(table(size(iCar)), xlab=&quot;itemset size&quot;, ylab=&quot;count&quot;)</code></pre>
<p><img src="car-arules_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>En el anterior gráfico podemos ver como la mayor parte de los ítemsets frecuentes son de tamaño 3 y 4, por lo que todo apunta a que podremos obtener buenas reglas y de un tamaño aceptable para sacar conclusiones en nuestro proceso de evaluación de coches.</p>
<p>En esta caso, los ítems no son muchos, por lo que podríamos quedarnos con ellos sin problema. Por otro lado, en caso de tener una set de ítems mayor, podríamos usar los ítems maximales o cerrados. Para obtener estos, el paquete apriori nos ofrece funciones fáciles de usar como sigue:</p>
<ul>
<li><strong>Maximales</strong>:</li>
</ul>
<pre class="r"><code>imaxCar &lt;- iCar[is.maximal(iCar)]
imaxCar</code></pre>
<pre><code>## set of 1000 itemsets</code></pre>
<pre class="r"><code>inspect(head(sort(imaxCar, by=&quot;support&quot;)))</code></pre>
<pre><code>##     items               support count
## [1] {pasajeros=more,                 
##      maletero=big,                   
##      seguridad=low,                  
##      clase=unacc}    0.03703704    64
## [2] {pasajeros=more,                 
##      maletero=med,                   
##      seguridad=low,                  
##      clase=unacc}    0.03703704    64
## [3] {pasajeros=more,                 
##      maletero=small,                 
##      seguridad=low,                  
##      clase=unacc}    0.03703704    64
## [4] {pasajeros=4,                    
##      maletero=big,                   
##      seguridad=low,                  
##      clase=unacc}    0.03703704    64
## [5] {pasajeros=4,                    
##      maletero=med,                   
##      seguridad=low,                  
##      clase=unacc}    0.03703704    64
## [6] {pasajeros=4,                    
##      maletero=small,                 
##      seguridad=low,                  
##      clase=unacc}    0.03703704    64</code></pre>
<ul>
<li><strong>Cerrados</strong>:</li>
</ul>
<pre class="r"><code>icloCar &lt;- iCar[is.closed(iCar)]
icloCar</code></pre>
<pre><code>## set of 1950 itemsets</code></pre>
<pre class="r"><code>inspect(head(sort(icloCar, by=&quot;support&quot;)))</code></pre>
<pre><code>##     items            support   count
## [1] {clase=unacc}    0.7002315 1210 
## [2] {pasajeros=more} 0.3333333  576 
## [3] {pasajeros=4}    0.3333333  576 
## [4] {maletero=big}   0.3333333  576 
## [5] {maletero=med}   0.3333333  576 
## [6] {seguridad=high} 0.3333333  576</code></pre>
<p>Una vez obtenidos todos, vamos a representar con un gráfico el número de ítems de cada clase:</p>
<pre class="r"><code>barplot( c(frequent=length(iCar), closed=length(icloCar), 
           maximal=length(imaxCar)), ylab=&quot;count&quot;, xlab=&quot;itemsets&quot;)</code></pre>
<p><img src="car-arules_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>El gráfico muestra lo que según la teoría cabe esperar y es que los maximales, son los menos abundantes, frente a cerrados y frecuentes que siempre se dan de la mano, aunque siempre son estos segundos algo más abundantes en el dominio del problema.</p>
<p>Dado que tenemos todos estos conjuntos vamos a comprobar las premisas de eficiencia que instan a usar unos u otros, que en casi todos los casos se traducen en reducción del espacio que ocupan. Por ello, vamos a obtener los tamaños de cada uno de los objetos.</p>
<pre class="r"><code>object.size(iCar)</code></pre>
<pre><code>## 85384 bytes</code></pre>
<pre class="r"><code>object.size(icloCar)</code></pre>
<pre><code>## 82496 bytes</code></pre>
<pre class="r"><code>object.size(imaxCar)</code></pre>
<pre><code>## 49240 bytes</code></pre>
<p>En este caso, los tamaños son insignificantes, pero si extrapolaramos los datos a un problema real, que incluso pudiera ser catalogado como Big Data, tener una representación que nos permitiera ahorrar espacio de casi un 50%, (como es el caso de los ítems maximales en nuestro problema), seguramente los beneficios fuerán mayores y necesarios de tener en cuenta.</p>
</div>
<div id="reglas-de-asociacion" class="section level2">
<h2>5 Reglas de asociación</h2>
<p>En este punto usaremos el método apriori para obtener las reglas de asociación. Esta es la parte esencial de la práctica y trataremos de evaluar cuando un coche es bueno y cuando es malo mediante estos métodos.</p>
<pre class="r"><code>rules &lt;- apriori(car, parameter = list(support = 0.01, confidence = 0.8, minlen = 2))</code></pre>
<pre><code>## Apriori
## 
## Parameter specification:
##  confidence minval smax arem  aval originalSupport maxtime support minlen
##         0.8    0.1    1 none FALSE            TRUE       5    0.01      2
##  maxlen target   ext
##      10  rules FALSE
## 
## Algorithmic control:
##  filter tree heap memopt load sort verbose
##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
## 
## Absolute minimum support count: 17 
## 
## set item appearances ...[0 item(s)] done [0.00s].
## set transactions ...[25 item(s), 1728 transaction(s)] done [0.00s].
## sorting and recoding items ... [25 item(s)] done [0.00s].
## creating transaction tree ... done [0.00s].
## checking subsets of size 1 2 3 4 done [0.00s].
## writing ... [415 rule(s)] done [0.00s].
## creating S4 object  ... done [0.00s].</code></pre>
<pre class="r"><code>rules</code></pre>
<pre><code>## set of 415 rules</code></pre>
<p>Hemos obtenido 415 reglas de asociación, por lo que al no ser muchas, podremos estudiarlas sin mucha complejidad. Aún así, antes de entrar en el análisis vamos a eliminar las reglas redundantes, para no caer en el error de analizar dos veces la misma regla.</p>
<pre class="r"><code>rulesSorted = sort(rules, by = &quot;confidence&quot;)
subsetMatrix &lt;- is.subset(rulesSorted, rulesSorted)
subsetMatrix[lower.tri(subsetMatrix, diag=TRUE)] &lt;- FALSE
redundant &lt;- colSums(subsetMatrix, na.rm=TRUE) &gt;= 1
rulesPruned &lt;- rulesSorted[!redundant] 
rulesPruned</code></pre>
<pre><code>## set of 38 rules</code></pre>
<p>Reglas no redundantes, aparecen solo 38. Esto ha simplificado el problema aún más, tanto que incluso podríamos llegar a pensar que el dataset no es apropiado ya que no ofrece muchas caracteristicas descriptivas.</p>
<p>Antes de entrar en el análisis de las reglas, en un dominio donde el número de estas sea muy abundante puede ser de especial utilidad obtener visualmente información sobre el número de reglas y la bondaz de las mismas. Para ello, podemos apoyarnos en gráficos:</p>
<pre class="r"><code>library(arulesViz)
plot(rulesPruned, method=&quot;two-key plot&quot;)</code></pre>
<p><img src="car-arules_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>En este gráfico, podemos ver las reglas obtenidas, el tamaño de las mismas y como se situan en función del soporte y la confianza. Algo muy util incluso para ver ciertos patrones, como por ejemplo, comprobar como las reglas de mayor número de ítems se situan con valores menores de soporte. Una vez vista la distribucion de las reglas obtenidas vamos a inspeccionarlas manualmente:</p>
<pre class="r"><code>inspect(rulesPruned)</code></pre>
<pre><code>##      lhs                             rhs                           support confidence     lift count
## [1]  {clase=vgood}                =&gt; {seguridad=high}           0.03761574  1.0000000 3.000000    65
## [2]  {seguridad=low}              =&gt; {clase=unacc}              0.33333333  1.0000000 1.428099   576
## [3]  {pasajeros=2}                =&gt; {clase=unacc}              0.33333333  1.0000000 1.428099   576
## [4]  {precio-compra=med,                                                                            
##       clase=good}                 =&gt; {precio-mantenimiento=low} 0.01331019  1.0000000 4.000000    23
## [5]  {precio-mantenimiento=med,                                                                     
##       clase=good}                 =&gt; {precio-compra=low}        0.01331019  1.0000000 4.000000    23
## [6]  {maletero=big,                                                                                 
##       clase=good}                 =&gt; {seguridad=med}            0.01388889  1.0000000 3.000000    24
## [7]  {maletero=small,                                                                               
##       clase=good}                 =&gt; {seguridad=high}           0.01215278  1.0000000 3.000000    21
## [8]  {precio-compra=vhigh,                                                                          
##       precio-mantenimiento=high}  =&gt; {clase=unacc}              0.06250000  1.0000000 1.428099   108
## [9]  {precio-compra=vhigh,                                                                          
##       precio-mantenimiento=vhigh} =&gt; {clase=unacc}              0.06250000  1.0000000 1.428099   108
## [10] {precio-compra=high,                                                                           
##       precio-mantenimiento=vhigh} =&gt; {clase=unacc}              0.06250000  1.0000000 1.428099   108
## [11] {precio-compra=high,                                                                           
##       maletero=small,                                                                               
##       clase=acc}                  =&gt; {seguridad=high}           0.01215278  1.0000000 3.000000    21
## [12] {precio-compra=vhigh,                                                                          
##       maletero=small,                                                                               
##       seguridad=med}              =&gt; {clase=unacc}              0.02777778  1.0000000 1.428099    48
## [13] {precio-compra=high,                                                                           
##       maletero=small,                                                                               
##       seguridad=med}              =&gt; {clase=unacc}              0.02777778  1.0000000 1.428099    48
## [14] {puertas=2,                                                                                    
##       pasajeros=more,                                                                               
##       maletero=small}             =&gt; {clase=unacc}              0.02777778  1.0000000 1.428099    48
## [15] {precio-mantenimiento=vhigh,                                                                   
##       maletero=small,                                                                               
##       seguridad=med}              =&gt; {clase=unacc}              0.02777778  1.0000000 1.428099    48
## [16] {precio-compra=vhigh,                                                                          
##       puertas=2,                                                                                    
##       maletero=small}             =&gt; {clase=unacc}              0.01967593  0.9444444 1.348760    34
## [17] {precio-mantenimiento=vhigh,                                                                   
##       puertas=2,                                                                                    
##       maletero=small}             =&gt; {clase=unacc}              0.01967593  0.9444444 1.348760    34
## [18] {precio-compra=high,                                                                           
##       puertas=2,                                                                                    
##       maletero=small}             =&gt; {clase=unacc}              0.01909722  0.9166667 1.309091    33
## [19] {precio-compra=vhigh,                                                                          
##       maletero=small}             =&gt; {clase=unacc}              0.07523148  0.9027778 1.289256   130
## [20] {precio-mantenimiento=vhigh,                                                                   
##       maletero=small}             =&gt; {clase=unacc}              0.07523148  0.9027778 1.289256   130
## [21] {puertas=2,                                                                                    
##       maletero=small,                                                                               
##       seguridad=med}              =&gt; {clase=unacc}              0.02488426  0.8958333 1.279339    43
## [22] {precio-compra=vhigh,                                                                          
##       puertas=2,                                                                                    
##       maletero=med}               =&gt; {clase=unacc}              0.01851852  0.8888889 1.269421    32
## [23] {precio-compra=vhigh,                                                                          
##       puertas=2,                                                                                    
##       seguridad=med}              =&gt; {clase=unacc}              0.01851852  0.8888889 1.269421    32
## [24] {precio-mantenimiento=high,                                                                    
##       puertas=2,                                                                                    
##       maletero=small}             =&gt; {clase=unacc}              0.01851852  0.8888889 1.269421    32
## [25] {precio-mantenimiento=vhigh,                                                                   
##       puertas=2,                                                                                    
##       maletero=med}               =&gt; {clase=unacc}              0.01851852  0.8888889 1.269421    32
## [26] {precio-mantenimiento=vhigh,                                                                   
##       puertas=2,                                                                                    
##       seguridad=med}              =&gt; {clase=unacc}              0.01851852  0.8888889 1.269421    32
## [27] {puertas=2,                                                                                    
##       maletero=small}             =&gt; {clase=unacc}              0.07291667  0.8750000 1.249587   126
## [28] {precio-compra=vhigh,                                                                          
##       puertas=2}                  =&gt; {clase=unacc}              0.05439815  0.8703704 1.242975    94
## [29] {precio-mantenimiento=vhigh,                                                                   
##       puertas=2}                  =&gt; {clase=unacc}              0.05439815  0.8703704 1.242975    94
## [30] {precio-compra=high,                                                                           
##       maletero=small}             =&gt; {clase=unacc}              0.07118056  0.8541667 1.219835   123
## [31] {precio-mantenimiento=high,                                                                    
##       maletero=small,                                                                               
##       seguridad=med}              =&gt; {clase=unacc}              0.02372685  0.8541667 1.219835    41
## [32] {precio-compra=vhigh}        =&gt; {clase=unacc}              0.20833333  0.8333333 1.190083   360
## [33] {precio-mantenimiento=vhigh} =&gt; {clase=unacc}              0.20833333  0.8333333 1.190083   360
## [34] {precio-compra=high,                                                                           
##       puertas=2,                                                                                    
##       maletero=med}               =&gt; {clase=unacc}              0.01736111  0.8333333 1.190083    30
## [35] {precio-compra=high,                                                                           
##       puertas=2,                                                                                    
##       seguridad=med}              =&gt; {clase=unacc}              0.01736111  0.8333333 1.190083    30
## [36] {maletero=small,                                                                               
##       seguridad=med}              =&gt; {clase=unacc}              0.09085648  0.8177083 1.167769   157
## [37] {precio-compra=high,                                                                           
##       puertas=2}                  =&gt; {clase=unacc}              0.05034722  0.8055556 1.150413    87
## [38] {precio-mantenimiento=high,                                                                    
##       maletero=small}             =&gt; {clase=unacc}              0.06712963  0.8055556 1.150413   116</code></pre>
<p>Si analizamos las relglas obtenidas, parece que hemos tenido un claro sesgo hacia nuestra clase mayoritaria y obtenemos reglas aceptables que nos llevan a saber cuando un coche no es apropiado. Deberemos afinar un poco más el proceso de obtención de reglas para obtener informacion que realmente aporte valor. Esto podrá hacerse probablemente, realizando un estudio basado en generalización o jerarquización de reglas.</p>
<p>Aún así, aunque este set de reglas no nos ayuda mucho con nuestra premisa inicial de ver cuando un coche será evaluado como bueno, sí que nos ayuda para obtener información acerca de cuando un determinado vehiculo tendrá evaluación negativa, ademas de darnos información curiosa aunque ciertamente trivial como la regla * [1] {clase=vgood} =&gt; {seguridad=high} * que nos indica que si la evaluación del vehículo es muy buena, la seguridad será muy alta. Por otro lado, volvemos a tener un claro ejemplo en como los coches ‘deportivos’ serán evaluados como malos en este problema, ya que tenemos reglas del tipo <em><span precio-compra="vhigh,puertas=2,maletero=small">16</span> =&gt; {clase=unacc}</em>, donde ahora sin ningun tipo de duda estamos ante este tipo de coches, precios altos, 2 puertas y maleteros pequeños implicarán clases malas.</p>
<p>Dado que lo que nos interesa es ver cuando será una evaluaciona aceptable y cuando no, en los próximos puntos realizaremos un análisis más exhaustivo para intentar obtener aún mejor información y representarla graficamente.</p>
</div>
<div id="enfoques-avanzados" class="section level2">
<h2>7 Enfoques avanzados</h2>
<div id="reglas-generalizadas-o-gerarquicas" class="section level3">
<h3>7.1 Reglas generalizadas o gerarquicas</h3>
<p>Dado que los resultados vistos anteriormente no son muy buenos, se nos presenta la posibilidad de hacer las siguientes generalizaciones para ver si obtenemos mejores resultados:</p>
<p>*Clase=unacc -&gt; Clase=MalaEvaluacion</p>
<p>*Clase=acc, Clase=good y Clase=vgood -&gt; Clase=BuenaEvaluacion</p>
<p>Para realizar este paso, primero copiaremos en dataset (para evitar modificar el original), cambiaremos estos valores y tras ello obtendremos de nuevo las reglas.</p>
<pre class="r"><code>cargeneralizazo&lt;-car
cargeneralizazo$clase&lt;-ifelse(cargeneralizazo$clase==&quot;unacc&quot;,&quot;MalaEvaluacion&quot;,&quot;BuenaEvaluacion&quot;)
cargeneralizazo$clase&lt;-as.factor(cargeneralizazo$clase)
head(cargeneralizazo,5)</code></pre>
<pre><code>##   precio-compra precio-mantenimiento puertas pasajeros maletero seguridad
## 1         vhigh                vhigh       2         2    small       low
## 2         vhigh                vhigh       2         2    small       med
## 3         vhigh                vhigh       2         2    small      high
## 4         vhigh                vhigh       2         2      med       low
## 5         vhigh                vhigh       2         2      med       med
##            clase
## 1 MalaEvaluacion
## 2 MalaEvaluacion
## 3 MalaEvaluacion
## 4 MalaEvaluacion
## 5 MalaEvaluacion</code></pre>
<p>Una vez hecho el cambio, obtendremos nuestras transacciones y reglas de asociación.</p>
<pre class="r"><code>cargeneralizazo.transactions &lt;- as(cargeneralizazo, &quot;transactions&quot;)

rules.generalizadas &lt;- apriori(cargeneralizazo.transactions, 
                               parameter = list(support = 0.01, confidence = 0.8, minlen = 2))</code></pre>
<pre><code>## Apriori
## 
## Parameter specification:
##  confidence minval smax arem  aval originalSupport maxtime support minlen
##         0.8    0.1    1 none FALSE            TRUE       5    0.01      2
##  maxlen target   ext
##      10  rules FALSE
## 
## Algorithmic control:
##  filter tree heap memopt load sort verbose
##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
## 
## Absolute minimum support count: 17 
## 
## set item appearances ...[0 item(s)] done [0.00s].
## set transactions ...[23 item(s), 1728 transaction(s)] done [0.00s].
## sorting and recoding items ... [23 item(s)] done [0.00s].
## creating transaction tree ... done [0.00s].
## checking subsets of size 1 2 3 4 done [0.00s].
## writing ... [421 rule(s)] done [0.00s].
## creating S4 object  ... done [0.00s].</code></pre>
<pre class="r"><code>rules.generalizadas</code></pre>
<pre><code>## set of 421 rules</code></pre>
<p>Parece que obtenemos alguna reglas más que anterioremente. Vamos a filtrarlas por no redundantes e intentar obtener información de ellas.</p>
<pre class="r"><code>rulesSorted = sort(rules.generalizadas, by = &quot;confidence&quot;)
subsetMatrix &lt;- is.subset(rulesSorted, rulesSorted)
subsetMatrix[lower.tri(subsetMatrix, diag=TRUE)] &lt;- FALSE
redundant &lt;- colSums(subsetMatrix, na.rm=TRUE) &gt;= 1
rulesPruned &lt;- rulesSorted[!redundant] 
inspect(rulesPruned)</code></pre>
<pre><code>##      lhs                             rhs                        support confidence     lift count
## [1]  {seguridad=low}              =&gt; {clase=MalaEvaluacion}  0.33333333  1.0000000 1.428099   576
## [2]  {pasajeros=2}                =&gt; {clase=MalaEvaluacion}  0.33333333  1.0000000 1.428099   576
## [3]  {precio-compra=vhigh,                                                                       
##       precio-mantenimiento=high}  =&gt; {clase=MalaEvaluacion}  0.06250000  1.0000000 1.428099   108
## [4]  {precio-compra=vhigh,                                                                       
##       precio-mantenimiento=vhigh} =&gt; {clase=MalaEvaluacion}  0.06250000  1.0000000 1.428099   108
## [5]  {precio-compra=high,                                                                        
##       precio-mantenimiento=vhigh} =&gt; {clase=MalaEvaluacion}  0.06250000  1.0000000 1.428099   108
## [6]  {precio-compra=vhigh,                                                                       
##       maletero=small,                                                                            
##       seguridad=med}              =&gt; {clase=MalaEvaluacion}  0.02777778  1.0000000 1.428099    48
## [7]  {precio-compra=med,                                                                         
##       pasajeros=4,                                                                               
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02777778  1.0000000 3.335907    48
## [8]  {precio-compra=high,                                                                        
##       maletero=small,                                                                            
##       clase=BuenaEvaluacion}      =&gt; {seguridad=high}        0.01215278  1.0000000 3.000000    21
## [9]  {precio-compra=high,                                                                        
##       maletero=small,                                                                            
##       seguridad=med}              =&gt; {clase=MalaEvaluacion}  0.02777778  1.0000000 1.428099    48
## [10] {precio-mantenimiento=low,                                                                  
##       pasajeros=4,                                                                               
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02777778  1.0000000 3.335907    48
## [11] {precio-mantenimiento=med,                                                                  
##       pasajeros=4,                                                                               
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02777778  1.0000000 3.335907    48
## [12] {puertas=2,                                                                                 
##       maletero=small,                                                                            
##       clase=BuenaEvaluacion}      =&gt; {pasajeros=4}           0.01041667  1.0000000 3.000000    18
## [13] {puertas=2,                                                                                 
##       pasajeros=more,                                                                            
##       maletero=small}             =&gt; {clase=MalaEvaluacion}  0.02777778  1.0000000 1.428099    48
## [14] {precio-mantenimiento=vhigh,                                                                
##       maletero=small,                                                                            
##       seguridad=med}              =&gt; {clase=MalaEvaluacion}  0.02777778  1.0000000 1.428099    48
## [15] {precio-compra=low,                                                                         
##       pasajeros=4,                                                                               
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02777778  1.0000000 3.335907    48
## [16] {precio-compra=vhigh,                                                                       
##       puertas=2,                                                                                 
##       maletero=small}             =&gt; {clase=MalaEvaluacion}  0.01967593  0.9444444 1.348760    34
## [17] {precio-mantenimiento=vhigh,                                                                
##       puertas=2,                                                                                 
##       maletero=small}             =&gt; {clase=MalaEvaluacion}  0.01967593  0.9444444 1.348760    34
## [18] {precio-compra=med,                                                                         
##       pasajeros=more,                                                                            
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02546296  0.9166667 3.057915    44
## [19] {precio-compra=high,                                                                        
##       puertas=2,                                                                                 
##       maletero=small}             =&gt; {clase=MalaEvaluacion}  0.01909722  0.9166667 1.309091    33
## [20] {precio-mantenimiento=low,                                                                  
##       pasajeros=more,                                                                            
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02546296  0.9166667 3.057915    44
## [21] {precio-mantenimiento=med,                                                                  
##       pasajeros=more,                                                                            
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02546296  0.9166667 3.057915    44
## [22] {precio-compra=low,                                                                         
##       pasajeros=more,                                                                            
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02546296  0.9166667 3.057915    44
## [23] {precio-compra=vhigh,                                                                       
##       maletero=small}             =&gt; {clase=MalaEvaluacion}  0.07523148  0.9027778 1.289256   130
## [24] {precio-mantenimiento=vhigh,                                                                
##       maletero=small}             =&gt; {clase=MalaEvaluacion}  0.07523148  0.9027778 1.289256   130
## [25] {puertas=2,                                                                                 
##       maletero=small,                                                                            
##       seguridad=med}              =&gt; {clase=MalaEvaluacion}  0.02488426  0.8958333 1.279339    43
## [26] {precio-compra=vhigh,                                                                       
##       puertas=2,                                                                                 
##       maletero=med}               =&gt; {clase=MalaEvaluacion}  0.01851852  0.8888889 1.269421    32
## [27] {precio-compra=vhigh,                                                                       
##       puertas=2,                                                                                 
##       seguridad=med}              =&gt; {clase=MalaEvaluacion}  0.01851852  0.8888889 1.269421    32
## [28] {precio-mantenimiento=high,                                                                 
##       puertas=2,                                                                                 
##       maletero=small}             =&gt; {clase=MalaEvaluacion}  0.01851852  0.8888889 1.269421    32
## [29] {precio-mantenimiento=vhigh,                                                                
##       puertas=2,                                                                                 
##       maletero=med}               =&gt; {clase=MalaEvaluacion}  0.01851852  0.8888889 1.269421    32
## [30] {precio-mantenimiento=vhigh,                                                                
##       puertas=2,                                                                                 
##       seguridad=med}              =&gt; {clase=MalaEvaluacion}  0.01851852  0.8888889 1.269421    32
## [31] {puertas=2,                                                                                 
##       maletero=small}             =&gt; {clase=MalaEvaluacion}  0.07291667  0.8750000 1.249587   126
## [32] {precio-compra=low,                                                                         
##       pasajeros=4,                                                                               
##       seguridad=med}              =&gt; {clase=BuenaEvaluacion} 0.02430556  0.8750000 2.918919    42
## [33] {precio-compra=vhigh,                                                                       
##       puertas=2}                  =&gt; {clase=MalaEvaluacion}  0.05439815  0.8703704 1.242975    94
## [34] {precio-mantenimiento=vhigh,                                                                
##       puertas=2}                  =&gt; {clase=MalaEvaluacion}  0.05439815  0.8703704 1.242975    94
## [35] {precio-compra=high,                                                                        
##       maletero=small}             =&gt; {clase=MalaEvaluacion}  0.07118056  0.8541667 1.219835   123
## [36] {precio-mantenimiento=high,                                                                 
##       maletero=small,                                                                            
##       seguridad=med}              =&gt; {clase=MalaEvaluacion}  0.02372685  0.8541667 1.219835    41
## [37] {precio-compra=vhigh}        =&gt; {clase=MalaEvaluacion}  0.20833333  0.8333333 1.190083   360
## [38] {precio-mantenimiento=vhigh} =&gt; {clase=MalaEvaluacion}  0.20833333  0.8333333 1.190083   360
## [39] {precio-compra=high,                                                                        
##       puertas=2,                                                                                 
##       maletero=med}               =&gt; {clase=MalaEvaluacion}  0.01736111  0.8333333 1.190083    30
## [40] {precio-compra=high,                                                                        
##       puertas=2,                                                                                 
##       seguridad=med}              =&gt; {clase=MalaEvaluacion}  0.01736111  0.8333333 1.190083    30
## [41] {precio-compra=low,                                                                         
##       pasajeros=more,                                                                            
##       seguridad=med}              =&gt; {clase=BuenaEvaluacion} 0.02314815  0.8333333 2.779923    40
## [42] {maletero=small,                                                                            
##       seguridad=med}              =&gt; {clase=MalaEvaluacion}  0.09085648  0.8177083 1.167769   157
## [43] {pasajeros=4,                                                                               
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.09027778  0.8125000 2.710425   156
## [44] {puertas=5more,                                                                             
##       pasajeros=more,                                                                            
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02256944  0.8125000 2.710425    39
## [45] {puertas=4,                                                                                 
##       pasajeros=more,                                                                            
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02256944  0.8125000 2.710425    39
## [46] {puertas=3,                                                                                 
##       pasajeros=more,                                                                            
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.02256944  0.8125000 2.710425    39
## [47] {pasajeros=more,                                                                            
##       maletero=med,                                                                              
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [48] {pasajeros=4,                                                                               
##       maletero=big,                                                                              
##       seguridad=med}              =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [49] {pasajeros=more,                                                                            
##       maletero=big,                                                                              
##       seguridad=high}             =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [50] {pasajeros=more,                                                                            
##       maletero=big,                                                                              
##       seguridad=med}              =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [51] {precio-compra=high,                                                                        
##       puertas=2}                  =&gt; {clase=MalaEvaluacion}  0.05034722  0.8055556 1.150413    87
## [52] {precio-mantenimiento=high,                                                                 
##       maletero=small}             =&gt; {clase=MalaEvaluacion}  0.06712963  0.8055556 1.150413   116</code></pre>
<p>Parece que nuestro proceso de generalización de reglas ha surtido efecto y tenemos ya presencia de clase=BuenaEvaluacion en los consecuentes, que es la premisa que buscamos, es decir, ver cuando un coche será bien evaluado en función de sus características. Una función interesante para evaluar las reglas estará también en encontrar aquellas que están relacioandas con determinados ítems. Por ejemplo vamos a construir dos sets de reglas, uno para los de la clase MalaEvaluación y otro para los de la clase BuenaEvaluación.</p>
<pre class="r"><code>rules.malaeval&lt;- apriori (cargeneralizazo, parameter=list(supp=0.01,conf = 0.8), 
                          appearance =list (default=&quot;lhs&quot;,rhs=&quot;clase=MalaEvaluacion&quot;), 
                          control = list (verbose=F))

rules.buenaeval&lt;- apriori (cargeneralizazo, parameter=list(supp=0.01,conf = 0.8),
                           appearance =list (default=&quot;lhs&quot;,rhs=&quot;clase=BuenaEvaluacion&quot;), 
                           control = list (verbose=F))</code></pre>
<p>Ahora limpiaremos los sets de reglas redundantes.</p>
<pre class="r"><code>#Mala evaluación
rulesSorted = sort(rules.malaeval, by = &quot;confidence&quot;)
subsetMatrix &lt;- is.subset(rulesSorted, rulesSorted)
subsetMatrix[lower.tri(subsetMatrix, diag=TRUE)] &lt;- FALSE
redundant &lt;- colSums(subsetMatrix, na.rm=TRUE) &gt;= 1
rulesPrunedMala &lt;- rulesSorted[!redundant] 

#Buena evaluación

rulesSorted = sort(rules.buenaeval, by = &quot;confidence&quot;)
subsetMatrix &lt;- is.subset(rulesSorted, rulesSorted)
subsetMatrix[lower.tri(subsetMatrix, diag=TRUE)] &lt;- FALSE
redundant &lt;- colSums(subsetMatrix, na.rm=TRUE) &gt;= 1
rulesPrunedBuena &lt;- rulesSorted[!redundant] </code></pre>
<p>Por último, mostramos las reglas y las estudiamos:</p>
<pre class="r"><code>inspect(rulesPrunedBuena)</code></pre>
<pre><code>##      lhs                           rhs                        support confidence     lift count
## [1]  {precio-compra=low,                                                                       
##       pasajeros=4,                                                                             
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02777778  1.0000000 3.335907    48
## [2]  {precio-compra=med,                                                                       
##       pasajeros=4,                                                                             
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02777778  1.0000000 3.335907    48
## [3]  {precio-mantenimiento=low,                                                                
##       pasajeros=4,                                                                             
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02777778  1.0000000 3.335907    48
## [4]  {precio-mantenimiento=med,                                                                
##       pasajeros=4,                                                                             
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02777778  1.0000000 3.335907    48
## [5]  {precio-compra=low,                                                                       
##       pasajeros=more,                                                                          
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02546296  0.9166667 3.057915    44
## [6]  {precio-compra=med,                                                                       
##       pasajeros=more,                                                                          
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02546296  0.9166667 3.057915    44
## [7]  {precio-mantenimiento=low,                                                                
##       pasajeros=more,                                                                          
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02546296  0.9166667 3.057915    44
## [8]  {precio-mantenimiento=med,                                                                
##       pasajeros=more,                                                                          
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02546296  0.9166667 3.057915    44
## [9]  {precio-compra=low,                                                                       
##       pasajeros=4,                                                                             
##       seguridad=med}            =&gt; {clase=BuenaEvaluacion} 0.02430556  0.8750000 2.918919    42
## [10] {precio-compra=low,                                                                       
##       pasajeros=more,                                                                          
##       seguridad=med}            =&gt; {clase=BuenaEvaluacion} 0.02314815  0.8333333 2.779923    40
## [11] {pasajeros=4,                                                                             
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.09027778  0.8125000 2.710425   156
## [12] {puertas=5more,                                                                           
##       pasajeros=more,                                                                          
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02256944  0.8125000 2.710425    39
## [13] {puertas=4,                                                                               
##       pasajeros=more,                                                                          
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02256944  0.8125000 2.710425    39
## [14] {puertas=3,                                                                               
##       pasajeros=more,                                                                          
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.02256944  0.8125000 2.710425    39
## [15] {pasajeros=4,                                                                             
##       maletero=big,                                                                            
##       seguridad=med}            =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [16] {pasajeros=more,                                                                          
##       maletero=big,                                                                            
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [17] {pasajeros=more,                                                                          
##       maletero=big,                                                                            
##       seguridad=med}            =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [18] {pasajeros=more,                                                                          
##       maletero=med,                                                                            
##       seguridad=high}           =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52</code></pre>
<p>Parece que nuestro proceso ha tenido utilidad y tenemos un buen set de reglas con valores bastante aceptables de medidas de bondaz. Vamos a estudiar algunas reglas interesantes:</p>
<ul>
<li><em>[16] {pasajeros=more,maletero=big,seguridad=high} =&gt; {clase=BuenaEvaluacion}</em><br />
</li>
<li><em>[17] {pasajeros=more,maletero=big,seguridad=med} =&gt; {clase=BuenaEvaluacion}</em></li>
<li><em>[18] {pasajeros=more,maletero=med,seguridad=high} =&gt; {clase=BuenaEvaluacion}</em></li>
</ul>
<p>Estas tres reglas, confirman la teoria que teníamos anteriormente de que en el proceso de evaluación se están teniendo en cuenta coches serviciales frente a coches lujosos, bonitos o rápidos. Al estudiar las reglas anteriores, es evidente, que estamos ante <em>coches familiares o del tipo monovolumen</em> y los cuales son bastante bien valorados a pesar de que otros factores como el tamaño o la seguridad pueda tomar valores dispares.</p>
<p>Otra regla interesante, puede ser la <em><span pasajeros="4,maletero=big,seguridad=med">15</span> =&gt; {clase=BuenaEvaluacion}</em>, donde vemos como la evaluación de un hipotético coche se permite descensos en seguridad pos de mayor tamaño.</p>
<p>Por otro lado, hay también reglas triviales que no nos dicen nada como pueden ser <em><span precio-compra="low,pasajeros=4,seguridad=high">1</span> =&gt; {clase=BuenaEvaluacion}</em> y <em><span precio-mantenimiento="low,pasajeros=4,seguridad=high">3</span> =&gt; {clase=BuenaEvaluacion}</em> donde podemos corroborar la típica expresión popular del “bueno, bonito y barato”, pero que no aporta valor ninguno.</p>
<p>También, puede obtenerse información por ausencia de reglas, es decir, podemos ver que no hay ninguna regla cuyo antecedente contenga el ítem <strong>seguridad=low</strong>, por lo que a muy seguro, este sea un ítem que determinará en la mayoría de los casos una mala evaluación. Para comprobar esta premisa, por último, vamos a estudiar las reglas para <strong>clase=MalaEvaluacion</strong>.</p>
<pre class="r"><code>inspect(rulesPrunedMala)</code></pre>
<pre><code>##      lhs                             rhs                       support confidence     lift count
## [1]  {seguridad=low}              =&gt; {clase=MalaEvaluacion} 0.33333333  1.0000000 1.428099   576
## [2]  {pasajeros=2}                =&gt; {clase=MalaEvaluacion} 0.33333333  1.0000000 1.428099   576
## [3]  {precio-compra=vhigh,                                                                      
##       precio-mantenimiento=vhigh} =&gt; {clase=MalaEvaluacion} 0.06250000  1.0000000 1.428099   108
## [4]  {precio-compra=vhigh,                                                                      
##       precio-mantenimiento=high}  =&gt; {clase=MalaEvaluacion} 0.06250000  1.0000000 1.428099   108
## [5]  {precio-compra=high,                                                                       
##       precio-mantenimiento=vhigh} =&gt; {clase=MalaEvaluacion} 0.06250000  1.0000000 1.428099   108
## [6]  {precio-compra=vhigh,                                                                      
##       maletero=small,                                                                           
##       seguridad=med}              =&gt; {clase=MalaEvaluacion} 0.02777778  1.0000000 1.428099    48
## [7]  {precio-mantenimiento=vhigh,                                                               
##       maletero=small,                                                                           
##       seguridad=med}              =&gt; {clase=MalaEvaluacion} 0.02777778  1.0000000 1.428099    48
## [8]  {puertas=2,                                                                                
##       pasajeros=more,                                                                           
##       maletero=small}             =&gt; {clase=MalaEvaluacion} 0.02777778  1.0000000 1.428099    48
## [9]  {precio-compra=high,                                                                       
##       maletero=small,                                                                           
##       seguridad=med}              =&gt; {clase=MalaEvaluacion} 0.02777778  1.0000000 1.428099    48
## [10] {precio-compra=vhigh,                                                                      
##       puertas=2,                                                                                
##       maletero=small}             =&gt; {clase=MalaEvaluacion} 0.01967593  0.9444444 1.348760    34
## [11] {precio-mantenimiento=vhigh,                                                               
##       puertas=2,                                                                                
##       maletero=small}             =&gt; {clase=MalaEvaluacion} 0.01967593  0.9444444 1.348760    34
## [12] {precio-compra=high,                                                                       
##       puertas=2,                                                                                
##       maletero=small}             =&gt; {clase=MalaEvaluacion} 0.01909722  0.9166667 1.309091    33
## [13] {precio-compra=vhigh,                                                                      
##       maletero=small}             =&gt; {clase=MalaEvaluacion} 0.07523148  0.9027778 1.289256   130
## [14] {precio-mantenimiento=vhigh,                                                               
##       maletero=small}             =&gt; {clase=MalaEvaluacion} 0.07523148  0.9027778 1.289256   130
## [15] {puertas=2,                                                                                
##       maletero=small,                                                                           
##       seguridad=med}              =&gt; {clase=MalaEvaluacion} 0.02488426  0.8958333 1.279339    43
## [16] {precio-compra=vhigh,                                                                      
##       puertas=2,                                                                                
##       maletero=med}               =&gt; {clase=MalaEvaluacion} 0.01851852  0.8888889 1.269421    32
## [17] {precio-compra=vhigh,                                                                      
##       puertas=2,                                                                                
##       seguridad=med}              =&gt; {clase=MalaEvaluacion} 0.01851852  0.8888889 1.269421    32
## [18] {precio-mantenimiento=vhigh,                                                               
##       puertas=2,                                                                                
##       maletero=med}               =&gt; {clase=MalaEvaluacion} 0.01851852  0.8888889 1.269421    32
## [19] {precio-mantenimiento=vhigh,                                                               
##       puertas=2,                                                                                
##       seguridad=med}              =&gt; {clase=MalaEvaluacion} 0.01851852  0.8888889 1.269421    32
## [20] {precio-mantenimiento=high,                                                                
##       puertas=2,                                                                                
##       maletero=small}             =&gt; {clase=MalaEvaluacion} 0.01851852  0.8888889 1.269421    32
## [21] {puertas=2,                                                                                
##       maletero=small}             =&gt; {clase=MalaEvaluacion} 0.07291667  0.8750000 1.249587   126
## [22] {precio-compra=vhigh,                                                                      
##       puertas=2}                  =&gt; {clase=MalaEvaluacion} 0.05439815  0.8703704 1.242975    94
## [23] {precio-mantenimiento=vhigh,                                                               
##       puertas=2}                  =&gt; {clase=MalaEvaluacion} 0.05439815  0.8703704 1.242975    94
## [24] {precio-compra=high,                                                                       
##       maletero=small}             =&gt; {clase=MalaEvaluacion} 0.07118056  0.8541667 1.219835   123
## [25] {precio-mantenimiento=high,                                                                
##       maletero=small,                                                                           
##       seguridad=med}              =&gt; {clase=MalaEvaluacion} 0.02372685  0.8541667 1.219835    41
## [26] {precio-compra=vhigh}        =&gt; {clase=MalaEvaluacion} 0.20833333  0.8333333 1.190083   360
## [27] {precio-mantenimiento=vhigh} =&gt; {clase=MalaEvaluacion} 0.20833333  0.8333333 1.190083   360
## [28] {precio-compra=high,                                                                       
##       puertas=2,                                                                                
##       maletero=med}               =&gt; {clase=MalaEvaluacion} 0.01736111  0.8333333 1.190083    30
## [29] {precio-compra=high,                                                                       
##       puertas=2,                                                                                
##       seguridad=med}              =&gt; {clase=MalaEvaluacion} 0.01736111  0.8333333 1.190083    30
## [30] {maletero=small,                                                                           
##       seguridad=med}              =&gt; {clase=MalaEvaluacion} 0.09085648  0.8177083 1.167769   157
## [31] {precio-compra=high,                                                                       
##       puertas=2}                  =&gt; {clase=MalaEvaluacion} 0.05034722  0.8055556 1.150413    87
## [32] {precio-mantenimiento=high,                                                                
##       maletero=small}             =&gt; {clase=MalaEvaluacion} 0.06712963  0.8055556 1.150413   116</code></pre>
<p>De primeras podemos comprobar la hipótesis planteada anteriormente, ya que la priemera regla obtenida nos indica que <em>{seguridad=low} =&gt; {clase=MalaEvaluacion}</em>, en un gran número de los casos.</p>
<p>También es interesante como <strong>puertas=2</strong> parece ser el factor predominante en las reglas que causen mala evaluación por lo que esta información podría ser utilizada por ejemplo en una compañia automovilística que fuera a lanzar un nuevo coche en un determinado sector y sabría que la evaluación que los usarios harán de el, aunque los tamaños sean del coche en sí talla media-grande, será con mucha probabilidad mala si no se remedia el factor de las puertas.</p>
<p>Aunque, como hemos podido comprobar, las reglas de asociación son muy descriptivas y fácilmente entendibles, en algunos casos puede ser complicado obtener información de las mismas, por lo que usaremos gráficos para ver si podemos obtener o representar de una manera más amable los resultados.</p>
<pre class="r"><code>plot(rulesPrunedBuena[1:10], method=&quot;graph&quot;)</code></pre>
<p><img src="car-arules_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Este gráfico se representa de manera poco útil debido al solapamient de los nodos, hubs y aristas. Por ello deberemos utilizar la opción engine=interactive, donde podremos mover los nodos y las artistas del gráfico a nuestra manera obteniendo una mejor representación como puede ser:</p>
<div class="figure">
<img src="image/in.png" alt="Representación en grafo con engine=interactive" />
<p class="caption">Representación en grafo con engine=interactive</p>
</div>
<p>A modo de ejemplo, en este gráfico podemos ver como si pasajeros=more, seuridad=med y precio-compra=low, entonces, la clase será buena.</p>
</div>
<div id="items-negados-y-analisis-por-grupos" class="section level3">
<h3>7.2 Ítems negados y Análisis por grupos</h3>
<p>Por último realizaremos un estudio de ítems negados y análisis por grupos. Para ello, tendremos que negar los ítems de nuestra base de datos en una especie de dummificación, por lo que podremos usar el paquete dummies para facilitar el proceso y construir nuestro dataset. Dado que la explosión de ítems puede ser muy elevada, solo lo realizaremos con dos variables, seguridad y puertas.</p>
<pre class="r"><code>library(dummies)
puertas&lt;-dummy(cargeneralizazo$puertas)
seguridad&lt;-dummy(cargeneralizazo$seguridad)
#Creamos el dataset
negados&lt;-cbind(&quot;precio-compra&quot;=as.character(cargeneralizazo$`precio-compra`), 
               &quot;precio-mantenimiento&quot;=as.character(cargeneralizazo$`precio-mantenimiento`),
               puertas, &quot;pasajeros&quot;=as.character(cargeneralizazo$pasajeros),
               &quot;maletero&quot;=as.character(cargeneralizazo$maletero), seguridad, 
               &quot;clase&quot;=as.character(cargeneralizazo$clase))
negados&lt;-as.data.frame(negados)</code></pre>
<p>Ahora tendremos que pasar los 1 y los 0 de las variables creadas a true o false tras lo cual, obtendremos los datos en un dataframe de factores para que las transacciones puedan obtenerse de manera correcta.</p>
<pre class="r"><code>negados[,c(3:6,9:11)]&lt;-ifelse(negados[,c(3:6,9:11)]==1,TRUE,FALSE)
#Por último pasamos a factor los datos y obtenemos las transacciones
negados&lt;-apply(negados, 2, as.factor)
negados&lt;-as.data.frame(negados)
str(negados)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1728 obs. of  12 variables:
##  $ precio-compra       : Factor w/ 4 levels &quot;high&quot;,&quot;low&quot;,&quot;med&quot;,..: 4 4 4 4 4 4 4 4 4 4 ...
##  $ precio-mantenimiento: Factor w/ 4 levels &quot;high&quot;,&quot;low&quot;,&quot;med&quot;,..: 4 4 4 4 4 4 4 4 4 4 ...
##  $ NA2                 : Factor w/ 2 levels &quot; TRUE&quot;,&quot;FALSE&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ NA3                 : Factor w/ 2 levels &quot; TRUE&quot;,&quot;FALSE&quot;: 2 2 2 2 2 2 2 2 2 2 ...
##  $ NA4                 : Factor w/ 2 levels &quot; TRUE&quot;,&quot;FALSE&quot;: 2 2 2 2 2 2 2 2 2 2 ...
##  $ NA5more             : Factor w/ 2 levels &quot; TRUE&quot;,&quot;FALSE&quot;: 2 2 2 2 2 2 2 2 2 2 ...
##  $ pasajeros           : Factor w/ 3 levels &quot;2&quot;,&quot;4&quot;,&quot;more&quot;: 1 1 1 1 1 1 1 1 1 2 ...
##  $ maletero            : Factor w/ 3 levels &quot;big&quot;,&quot;med&quot;,&quot;small&quot;: 3 3 3 2 2 2 1 1 1 3 ...
##  $ NAhigh              : Factor w/ 2 levels &quot; TRUE&quot;,&quot;FALSE&quot;: 2 2 1 2 2 1 2 2 1 2 ...
##  $ NAlow               : Factor w/ 2 levels &quot; TRUE&quot;,&quot;FALSE&quot;: 1 2 2 1 2 2 1 2 2 1 ...
##  $ NAmed               : Factor w/ 2 levels &quot; TRUE&quot;,&quot;FALSE&quot;: 2 1 2 2 1 2 2 1 2 2 ...
##  $ clase               : Factor w/ 2 levels &quot;BuenaEvaluacion&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
<p>Obtenemos las reglas de asociación (aumentando un poco el soporte, ya que de otro modo el número de estas es muy grande) y las limpiamos ya que ahora puede haber una gran representación de reglas que tengan el mismo significado.</p>
<pre class="r"><code>negados &lt;- as(negados, &quot;transactions&quot;)
rules.negadas &lt;- apriori(negados, parameter = list(support = 0.03, 
                                                  confidence = 0.8, 
                                                  minlen = 2))</code></pre>
<pre><code>## Apriori
## 
## Parameter specification:
##  confidence minval smax arem  aval originalSupport maxtime support minlen
##         0.8    0.1    1 none FALSE            TRUE       5    0.03      2
##  maxlen target   ext
##      10  rules FALSE
## 
## Algorithmic control:
##  filter tree heap memopt load sort verbose
##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
## 
## Absolute minimum support count: 51 
## 
## set item appearances ...[0 item(s)] done [0.00s].
## set transactions ...[30 item(s), 1728 transaction(s)] done [0.00s].
## sorting and recoding items ... [30 item(s)] done [0.00s].
## creating transaction tree ... done [0.00s].
## checking subsets of size 1 2 3 4 5 6 7 8 done [0.03s].
## writing ... [18858 rule(s)] done [0.01s].
## creating S4 object  ... done [0.01s].</code></pre>
<pre class="r"><code>rules.negadas</code></pre>
<pre><code>## set of 18858 rules</code></pre>
<p>Vemos como el número de reglas si que se ha disparado en este caso, obteniendo un total de 18858 reglas. Vamos a limpiarlas para no perder el tiempo con reglas similares.</p>
<pre class="r"><code>rulesSortedNegadas = sort(rules.negadas, by = &quot;confidence&quot;)
subsetMatrix &lt;- is.subset(rulesSortedNegadas, rulesSortedNegadas)
subsetMatrix[lower.tri(subsetMatrix, diag=TRUE)] &lt;- FALSE
redundant &lt;- colSums(subsetMatrix, na.rm=TRUE) &gt;= 1
rulesPrunedNegadas &lt;- rulesSortedNegadas[!redundant] 
rulesPrunedNegadas</code></pre>
<pre><code>## set of 236 rules</code></pre>
<p>Dado que nuevamente, tenemos set de reglas de tamaño suficientemente grande como para no poder ser analizadas todas manualmente, obtendremos solo aquellas con las clases en los consecuentes, ya que de otro modo, hay muchas reglas que meten ruido y no son para nada interesantes como estas<em>{puertas4= TRUE} =&gt; {puertas2=FALSE}</em>, <em>{puertas4= TRUE}=&gt;{puertas5more=FALSE}</em>, <em>{puertas4= TRUE} =&gt; {puertas3=FALSE}</em> y las demás combinaciones posibles de reglas de este tipo.</p>
<pre class="r"><code>rules.malaeval.negados&lt;- apriori(negados, parameter=list(supp=0.03,conf = 0.8), 
                          appearance =list (default=&quot;lhs&quot;,rhs=&quot;clase=MalaEvaluacion&quot;), 
                          control = list (verbose=F))

rules.buenaeval.negados&lt;- apriori(negados, parameter=list(supp=0.03,conf = 0.8),
                           appearance =list (default=&quot;lhs&quot;,rhs=&quot;clase=BuenaEvaluacion&quot;), 
                           control = list (verbose=F))

#Mala evaluación
rulesSorted = sort(rules.malaeval.negados, by = &quot;confidence&quot;)
subsetMatrix &lt;- is.subset(rulesSorted, rulesSorted)
subsetMatrix[lower.tri(subsetMatrix, diag=TRUE)] &lt;- FALSE
redundant &lt;- colSums(subsetMatrix, na.rm=TRUE) &gt;= 1
rulesPrunedMalaNegados &lt;- rulesSorted[!redundant] 
rulesPrunedMalaNegados</code></pre>
<pre><code>## set of 138 rules</code></pre>
<pre class="r"><code>#Buena evaluación

rulesSorted = sort(rules.buenaeval.negados, by = &quot;confidence&quot;)
subsetMatrix &lt;- is.subset(rulesSorted, rulesSorted)
subsetMatrix[lower.tri(subsetMatrix, diag=TRUE)] &lt;- FALSE
redundant &lt;- colSums(subsetMatrix, na.rm=TRUE) &gt;= 1
rulesPrunedBuenaNegados &lt;- rulesSorted[!redundant] 
rulesPrunedBuenaNegados</code></pre>
<pre><code>## set of 33 rules</code></pre>
<p>Por último, analizamos las reglas:</p>
<pre class="r"><code>inspect(rulesPrunedBuenaNegados)</code></pre>
<pre><code>##      lhs                           rhs                        support confidence     lift count
## [1]  {precio-compra=low,                                                                       
##       NA2=FALSE,                                                                               
##       pasajeros=more,                                                                          
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03993056  0.9583333 3.196911    69
## [2]  {precio-compra=low,                                                                       
##       NA2=FALSE,                                                                               
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03935185  0.9444444 3.150579    68
## [3]  {precio-compra=low,                                                                       
##       NA3=FALSE,                                                                               
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03935185  0.9444444 3.150579    68
## [4]  {precio-compra=low,                                                                       
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.05208333  0.9375000 3.127413    90
## [5]  {precio-compra=med,                                                                       
##       NA2=FALSE,                                                                               
##       pasajeros=more,                                                                          
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03819444  0.9166667 3.057915    66
## [6]  {precio-mantenimiento=low,                                                                
##       NA2=FALSE,                                                                               
##       pasajeros=more,                                                                          
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03819444  0.9166667 3.057915    66
## [7]  {precio-mantenimiento=med,                                                                
##       NA2=FALSE,                                                                               
##       pasajeros=more,                                                                          
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03819444  0.9166667 3.057915    66
## [8]  {precio-compra=med,                                                                       
##       NA2=FALSE,                                                                               
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03703704  0.8888889 2.965251    64
## [9]  {precio-compra=med,                                                                       
##       NA3=FALSE,                                                                               
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03703704  0.8888889 2.965251    64
## [10] {precio-mantenimiento=low,                                                                
##       NA2=FALSE,                                                                               
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03703704  0.8888889 2.965251    64
## [11] {precio-mantenimiento=low,                                                                
##       NA3=FALSE,                                                                               
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03703704  0.8888889 2.965251    64
## [12] {precio-mantenimiento=med,                                                                
##       NA2=FALSE,                                                                               
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03703704  0.8888889 2.965251    64
## [13] {precio-mantenimiento=med,                                                                
##       NA3=FALSE,                                                                               
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03703704  0.8888889 2.965251    64
## [14] {precio-compra=low,                                                                       
##       pasajeros=more,                                                                          
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.04861111  0.8750000 2.918919    84
## [15] {precio-compra=med,                                                                       
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.04861111  0.8750000 2.918919    84
## [16] {precio-mantenimiento=low,                                                                
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.04861111  0.8750000 2.918919    84
## [17] {precio-mantenimiento=med,                                                                
##       pasajeros=4,                                                                             
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.04861111  0.8750000 2.918919    84
## [18] {precio-compra=med,                                                                       
##       pasajeros=more,                                                                          
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.04629630  0.8333333 2.779923    80
## [19] {precio-mantenimiento=low,                                                                
##       pasajeros=more,                                                                          
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.04629630  0.8333333 2.779923    80
## [20] {precio-mantenimiento=med,                                                                
##       pasajeros=more,                                                                          
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.04629630  0.8333333 2.779923    80
## [21] {pasajeros=4,                                                                             
##       NAhigh= TRUE}             =&gt; {clase=BuenaEvaluacion} 0.09027778  0.8125000 2.710425   156
## [22] {pasajeros=4,                                                                             
##       maletero=big,                                                                            
##       NAmed= TRUE}              =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [23] {pasajeros=more,                                                                          
##       maletero=big,                                                                            
##       NAmed= TRUE}              =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [24] {pasajeros=more,                                                                          
##       maletero=med,                                                                            
##       NAhigh= TRUE}             =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [25] {pasajeros=more,                                                                          
##       maletero=big,                                                                            
##       NAhigh= TRUE}             =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [26] {NA2=FALSE,                                                                               
##       pasajeros=more,                                                                          
##       NAhigh= TRUE}             =&gt; {clase=BuenaEvaluacion} 0.06770833  0.8125000 2.710425   117
## [27] {pasajeros=4,                                                                             
##       maletero=big,                                                                            
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.06018519  0.8125000 2.710425   104
## [28] {pasajeros=more,                                                                          
##       maletero=big,                                                                            
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.06018519  0.8125000 2.710425   104
## [29] {pasajeros=4,                                                                             
##       NAlow=FALSE,                                                                             
##       NAmed=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.09027778  0.8125000 2.710425   156
## [30] {pasajeros=more,                                                                          
##       maletero=med,                                                                            
##       NAlow=FALSE,                                                                             
##       NAmed=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52
## [31] {NA2=FALSE,                                                                               
##       pasajeros=more,                                                                          
##       maletero=med,                                                                            
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.04513889  0.8125000 2.710425    78
## [32] {NA2=FALSE,                                                                               
##       pasajeros=more,                                                                          
##       NAlow=FALSE,                                                                             
##       NAmed=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.06770833  0.8125000 2.710425   117
## [33] {NA2=FALSE,                                                                               
##       NA3=FALSE,                                                                               
##       pasajeros=4,                                                                             
##       maletero=med,                                                                            
##       NAlow=FALSE}              =&gt; {clase=BuenaEvaluacion} 0.03009259  0.8125000 2.710425    52</code></pre>
<p>Básicamente todas las reglas que tenemos entre manos tienen ítems negados que corresponden a <strong>seguridadlow=FALSE</strong>, algo que era de esperar. Por otro lado, podemos comprobar la potencia de este método en reglas como <strong>{puertas2=FALSE,puertas3=FALSE,pasajeros=4,maletero=med,seguridadlow=FALSE} =&gt; {clase=BuenaEvaluacion}</strong> donde gracias a los ítems negados en una sola regla podemos deducir 4 reglas interesantes que serían:</p>
<ul>
<li><em>{puertas=4,pasajeros=4,maletero=med,seguridad=med} =&gt; {clase=BuenaEvaluacion}</em></li>
<li><em>{puertas=4,pasajeros=4,maletero=med,seguridad=high} =&gt; {clase=BuenaEvaluacion}</em></li>
<li><em>{puertas=5more,pasajeros=4,maletero=med,seguridad=med} =&gt; {clase=BuenaEvaluacion}</em></li>
<li><em>{puertas=5more,pasajeros=4,maletero=med,seguridad=high} =&gt; {clase=BuenaEvaluacion}</em></li>
</ul>
<pre class="r"><code>inspect(head(rulesPrunedMalaNegados,10))</code></pre>
<pre><code>##      lhs                             rhs                       support confidence     lift count
## [1]  {NAlow= TRUE}                =&gt; {clase=MalaEvaluacion} 0.33333333  1.0000000 1.428099   576
## [2]  {pasajeros=2}                =&gt; {clase=MalaEvaluacion} 0.33333333  1.0000000 1.428099   576
## [3]  {precio-compra=vhigh,                                                                      
##       precio-mantenimiento=high}  =&gt; {clase=MalaEvaluacion} 0.06250000  1.0000000 1.428099   108
## [4]  {precio-compra=high,                                                                       
##       precio-mantenimiento=vhigh} =&gt; {clase=MalaEvaluacion} 0.06250000  1.0000000 1.428099   108
## [5]  {precio-compra=vhigh,                                                                      
##       precio-mantenimiento=vhigh} =&gt; {clase=MalaEvaluacion} 0.06250000  1.0000000 1.428099   108
## [6]  {NAhigh=FALSE,                                                                             
##       NAmed=FALSE}                =&gt; {clase=MalaEvaluacion} 0.33333333  1.0000000 1.428099   576
## [7]  {precio-compra=high,                                                                       
##       maletero=small,                                                                           
##       NAhigh=FALSE}               =&gt; {clase=MalaEvaluacion} 0.05555556  1.0000000 1.428099    96
## [8]  {precio-mantenimiento=vhigh,                                                               
##       maletero=small,                                                                           
##       NAhigh=FALSE}               =&gt; {clase=MalaEvaluacion} 0.05555556  1.0000000 1.428099    96
## [9]  {precio-compra=vhigh,                                                                      
##       maletero=small,                                                                           
##       NAhigh=FALSE}               =&gt; {clase=MalaEvaluacion} 0.05555556  1.0000000 1.428099    96
## [10] {NA2= TRUE,                                                                                
##       maletero=small,                                                                           
##       NAhigh=FALSE}               =&gt; {clase=MalaEvaluacion} 0.05266204  0.9479167 1.353719    91</code></pre>
<p>Al inspeccionar estas reglas, nos encontramos con uno de los grandes problemas de los ítems negados y es que son muy redundantes, por ejemplo si nos fijamos en las reglas <em>{seguridadlow= TRUE} =&gt; {clase=MalaEvaluacion}</em> y <em>{seguridadhigh=FALSE,seguridadmed=FALSE} =&gt; {clase=MalaEvaluacion}</em>, tenemos entre manos la misma regla de asociacón ya que la negación de seguridadhigh y seguridadmed implica, aprobación de seguridadlow. Este problema, es muy complicado de ver e implica el tener conocimiento del problema, ya que un analista que no supiera que esta variable solo puede tomar 3 valores podría concluir en un error de análisis.</p>
<p>Por último, puede resultar interesante el <strong>análisis de reglas por grupos</strong> o parejas. Esto nos puede ayudar a descartar reglas o información que de primeras parecia importante pero en realidad no lo son. En nuestro caso, tenemos ítems negados en algunas variables y ademas tenemos la variable <em>clase</em>, que también podría ser negada, teniendo en cuenta que clase=MalaEvaluacion es la negacion de {clase=BuenaEvaluacion}.</p>
<p>Teniendo esto en cuenta, vamos a comprobar nuestra premisa de que las seguridadlow=TRUE implican siempre MalaEvaluacion:</p>
<p>Tenemos esta regla: {seguridadlow=TRUE} =&gt; {clase=MalaEvaluacion} es fuerte y ofrece buenos soportes de soporte y confianza, si las analizamos en conjunción con reglas que tengan {clase=BuenaEvaluacion} deberemos encontrar siempre en los consecuentes seguridadlow=FALSE, es decir, la negación de la anterior. Analizando el dataset podremos encontra varias reglas que cumplen esto como pueden ser:</p>
<ul>
<li><em>{precio-mantenimiento=low,pasajeros=4,seguridadlow=FALSE} =&gt; {clase=BuenaEvaluacion}</em></li>
<li><em>{precio-mantenimiento=med,pasajeros=4,seguridadlow=FALSE} =&gt; {clase=BuenaEvaluacion}</em></li>
</ul>
<p>En base a esto podríamos afirmar que en base a un análisis por grupos seguridadlow=TRUE implica siempre MalaEvaluacion.</p>
</div>
</div>
<div id="resumen" class="section level2">
<h2>8 Resumen</h2>
<p>Tras este estudio de reglas de asociación llevado a cabo, hemos podido constatar la potencia de las reglas como método descriptivo para la obtención de información en grandes conjuntos de datos. La potencia del método es tal, que incluso podremos obtener información relevante y catalogar la muestra sin tener nada de informaciÓn del tipo de datos ni su procedencia. Para ilustrar esto podemos tomar por ejemplo las conclusiones obtenidas de esta práctica, donde tras obtener ítems frecuentes y reglas ya sabiamos que aunque estamos evaluando coches, el tamaño y el nivel de utilidad de los coches sería mas relevante que aspectos de diseño.</p>
<p>Queda demostrada también la potencia de las reglas de asociación en el ámbito de la minería de datos y nos hace comprender mejor, porque son uno de los métodos que desde su nacimiento han sido más estudiados y extendidos a diferentes problemas.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
